### ISSUE TITLE
Lack of certain timezones in released version of ical4j-zoneinfo-outlook

### ISSUE THREAD

**Issue by archev** [ical4j/ical4j-zoneinfo-outlook#1]
Hello,

We are using ical4j in our code and find it very solid.

Recently we are facing issues with Microsoft Outlook and 
would like to change our timezone registry to ical4j-zoneinfo-outlook.

Unfortunately, newest released version of it in maven repostiory
http://mvnrepository.com/artifact/org.mnode.ical4j/ical4j-zoneinfo-outlook/1.0.3

lacks several timezones i.e. America/Creston. Are you planning to release updated version?(or could you do it if that’s not a problem?)

Thanks in advance

**Comment by benfortuna** [comment]
Hi,

I've just released the latest ical4j-zoneinfo-outlook with the latest updated definitions. Let me know if there is something missing.

regards,
ben
