### ISSUE TITLE
Tzinfo for Europe cities is missing

### ISSUE THREAD

**Issue by ykushch** [ical4j/ical4j-zoneinfo-outlook#11]
Let's take London city for example. There are no such city under `/src/main/resources/zoneinfo-outlook/Europe`. Is it broken update or something else?

**Comment by benfortuna** [comment]
Yes the zoneinfo parser failed due to a change in `Pacific/Fiji` timezone rules. I've applied a fix and will create a new release shortly.

Thanks for bringing to my attention.

**Comment by benfortuna** [comment]
Fix applied in release 2.0.4 - should be available in maven central shortly.

**Comment by ykushch** [comment]
Thanks for the update. It works now 🙂
