### ISSUE TITLE
Tzinfo for Europe cities is missing

### ISSUE THREAD

**Issue by ykushch** [ical4j/ical4j-zoneinfo-outlook#13]
Let's take London city for example. There is no such city under `/src/main/resources/zoneinfo-outlook/Europe`. Is it broken update or something else?
By the way, http://www.tzurl.org/ is not working.

**Comment by benfortuna** [comment]
I'm not sure where you're seeing the missing files - I checked the latest jar and the repo also has the European cities. Hopefully the tzurl.org site is fixed now so maybe retry.

**Comment by benfortuna** [comment]
tzurl.org should now be working. Closing issue, feel free to reopen if problem still exists.
