### ISSUE TITLE
Version 2.0.4 and 2.0.5 not available in Maven Central

### ISSUE THREAD

**Issue by evpaassen** [ical4j/ical4j-zoneinfo-outlook#20]
[The documentation](https://ical4j.github.io/ical4j-user-guide/maven/) states:
> All iCal4j artifacts may now be found in the maven central repository.

The latest version of [this library in Maven Central](https://search.maven.org/artifact/org.mnode.ical4j/ical4j-zoneinfo-outlook) seems to be v2.0.3. Two newer versions, v2.0.4 and v2.0.5 are available on JCenter, but [JCenter will be shut down on May 1st](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

Would it be possible to publish these versions to Maven Central too?

**Comment by evpaassen** [comment]
It's only three days until May 1st now, so this issue is starting to become quite urgent now. @benfortuna, could you please shed your light on this?

**Comment by benfortuna** [comment]
Apologies I didn't realise they haven't synced to maven Central. I'll try to sync these versions, however if unable I will probably just push a new version directly.

**Comment by benfortuna** [comment]
Ok I was able to sync 2.0.4, but 2.0.5 had some maven incompatibilities.

So I've created a new release - 2.1.0 that includes some fixes regarding symlinks and upgrade to 2021a tzdata.

It should appear shortly in maven central: https://search.maven.org/search?q=a:ical4j-zoneinfo-outlook

**Comment by evpaassen** [comment]
Thanks a lot for fixing this! :)
